PfBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: PfBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        image:
            type: text
    lifecycleCallbacks: {  }
