PfBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: PfBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: 255
        content:
            type: text
    lifecycleCallbacks: {  }
